### ISSUE TITLE
 cannot import name 'bps' from 'bps'

### ISSUE THREAD

**Issue by weiyutao886** [multimodallearning/hand-gesture-posture-position#1]
I installed the python BPS package, but the following error still occurred. Do you know why

Traceback (most recent call last):
  File "/share/home/wanghui/workspacce/wyt/hand/hand1/main/train.py", line 16, in <module>
    from model.model import TwoStreamLSTM
  File "/share/home/wanghui/workspacce/wyt/hand/hand1/main/model/model.py", line 4, in <module>
    from model.backbones.bps_densenet import BPSDensenet
  File "/share/home/wanghui/workspacce/wyt/hand/hand1/main/model/backbones/bps_densenet.py", line 5, in <module>
    from bps import bps
ImportError: cannot import name 'bps' from 'bps' (/share/home/wanghui/.local/lib/python3.7/site-packages/bps/__init__.py)

**Comment by weiyutao886** [comment]
I solved the above problems, but I encountered new problems
Traceback (most recent call last):
  File "/share/home/wanghui/workspacce/wyt/hand/hand1/main/train.py", line 16, in <module>
    from model.model import TwoStreamLSTM
  File "/share/home/wanghui/workspacce/wyt/hand/hand1/main/model/model.py", line 8, in <module>
    from model.backbones.pointnet2 import PointNet2
  File "/share/home/wanghui/workspacce/wyt/hand/hand1/main/model/backbones/pointnet2.py", line 6, in <module>
    from torch_geometric.nn import PointConv, fps, radius, global_max_pool
  File "/share/home/wanghui/.local/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/share/home/wanghui/.local/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/share/home/wanghui/.local/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/share/home/wanghui/.local/lib/python3.7/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/share/home/wanghui/.local/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /share/home/wanghui/.local/lib/python3.7/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_

**Comment by alexbgl** [comment]
Hi, thanks for your interest in our work.

There seems to be an issue with the installation of torch_geometric. As mentioned, the package is only needed for the use of PointNet++. As the simplest solution, I would therefore suggest commenting out line 6 in "model/backbones/pointnet2.py". For experiments including PointNet++, please check the installation of torch_geometric.

**Comment by weiyutao886** [comment]
thank you
